const AUMIGO = [
    {
        id: "01",
        nome: "APOLO",
        imagem: "dog1.png",
        espaço: " ",
        idade:"4 anos",
        raça:"Vira-lata",
        temperamento: "Dócil",
        tamanho: "Porte médio",
        castrado: "Sim",
        vacinado: "Sim"
    },
    {
        id: "02",
        nome: "Timão",
        imagem: "dog2.png",
        espaço: " ",
        idade:"7 anos",
        raça:"vira-lata",
        temperamento: "Energético",
        tamanho: "Porte pequeno",
        castrado: "Não",
        vacinado: "Sim"
    },
    {
        id: "03",
        nome: "Reginaldo",
        imagem: "dog3.png",
        espaço: " ",
        idade:"10 anos",
        raça:"vira-lata",
        temperamento: "Carinhoso",
        tamanho: "Porte médio",
        castrado: "Sim",
        vacinado: "Sim"
    },
    {
        id: "04",
        nome: "Fiat",
        imagem: "dog4.png",
        espaço: " ",
        idade:"3 anos",
        raça:"vira-lata",
        temperamento: "Cão de guarda",
        tamanho: "Porte pequeno",
        castrado: "Não",
        vacinado: "Sim"
    },
    {
        id: "05",
        nome: "Pumba",
        imagem: "dog5.png",
        espaço: " ",
        idade:"2 anos",
        raça:"Pug",
        temperamento: "Manhoso",
        tamanho: "Porte pequeno",
        castrado: "Sim",
        vacinado: "Sim"
    },
    {
        id: "06",
        nome: "Toddy",
        imagem: "dog6.png",
        espaço: " ",
        idade:"4 anos",
        raça:"Pincher",
        temperamento: "Endemoniado",
        tamanho: "Porte pequeno",
        castrado: "Não",
        vacinado: "Sim"
    },
    {
        id: "07",
        nome: "Belinha",
        imagem: "dog7.png",
        espaço: " ",
        idade:"5 anos",
        raça:"Lhasa Apso",
        temperamento: "Brincalhão",
        tamanho: "Porte pequeno",
        castrado: "Sim",
        vacinado: "Sim"
    },
    {
        id: "08",
        nome: "Deiso",
        imagem: "dog8.png",
        espaço: " ",
        idade:"7 anos",
        raça:"Lhasa Apso",
        temperamento: "Carinhoso",
        tamanho: "Porte pequeno",
        castrado: "Sim",
        vacinado: "Sim"
    },
    {
        id: "09",
        nome: "Pudim",
        imagem: "dog9.png",
        espaço: " ",
        idade:"1 ano",
        raça:"Lulu da Pomerânia",
        temperamento: "Agitado",
        tamanho: "Porte pequeno",
        castrado: "Não",
        vacinado: "Sim"
    },
    {
        id: "10",
        nome: "Rogerinho",
        imagem: "dog10.png",
        espaço: " ",
        idade:"10 meses",
        raça:"Bassê",
        temperamento: "Dócil",
        tamanho: "Porte médio",
        castrado: "Não",
        vacinado: "Sim"
    },
    {
        id: "11",
        nome: "Afonso",
        imagem: "dog11.png",
        espaço: " ",
        idade:"7 anos",
        raça:"vira-lata",
        temperamento: "Defensivo",
        tamanho: "Porte grande",
        castrado: "Sim",
        vacinado: "Sim"
    },
    {
        id: "12",
        nome: "Bob",
        imagem: "dog12.png",
        espaço: " ",
        idade:"9 meses",
        raça:"york shire",
        temperamento: "Dócil",
        tamanho: "Porte pequeno",
        castrado: "Não",
        vacinado: "Sim"
    }
]
export default AUMIGO;